### ISSUE TITLE
Should the program continue to use SQLite for tracking changes or should we move to MySQL?

### ISSUE THREAD

**Issue by piccoloser** [machspec/maintenance_tracker#2]
The database file we have in the legacy version of the program was poorly made (my bad). It will probably need to be updated regardless, but it'd be less than ideal if we lost everything they've logged so far.

@RussEfarmer has suggested we use MySQL instead, but I don't have much experience here, let alone with implementing it in Rust. If it's worth the extra effort, I say we go for it; however, if it doesn't make a notable difference, then it may not be worth the effort.

**Comment by odjacobs** [comment]
MySQL we have a server for it. No idea how rust connects to it, but everything else we have uses it.

**Comment by RussEfarmer** [comment]
As far as operation of the app there isn't a benefit for using MySQL over SQLite, but the issue is when backing up data, the SQLite file is perpetually locked for reading and writing by other applications while your application is running (limitation of SQLite). To back up the old one, I had to rely on volume shadow copy, which is a PITA. Using MySQL, its easy to just shovel everything out every night without having to worry about the file being locked.

**Comment by piccoloser** [comment]
> the SQLite file is perpetually locked for reading and writing by other applications while your application is running

Didn't think of that. If it simplifies making backups, then I'm learning hard towards MySQL. I'll leave this open for comment for a little bit and close it if nobody has any other input. Thanks!

**Comment by piccoloser** [comment]
Program now uses MySQL.
